apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZWNoYXBwLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJ0ZWNoYXBwIiwicGFzc3dvcmQiOiJFU2NuYnBZTXU1RmZRWU10MExONz1rdUtzeEd4ZnhDWSIsImVtYWlsIjoidWRheWthbnRockBnbWFpbC5jb20iLCJhdXRoIjoiZEdWamFHRndjRHBGVTJOdVluQlpUWFUxUm1aUldVMTBNRXhPTnoxcmRVdHplRWQ0Wm5oRFdRPT0ifX19
kind: Secret
metadata:  
  name: tech-acr-secret
  namespace: techchallenge
type: kubernetes.io/dockerconfigjson
